---
- name: Install
  hosts: all
  remote_user: logan
  become: yes
  vars:
    mongo_connection: "{{ mongo }}"
    jwt_key: "{{ jwt }}"
    binary_path: "{{ bin }}"
    aws_key: "{{ aws_key }}"
    aws_secret: "{{ aws_secret }}"
    api_port: 3000

  tasks:
    - name: Allow all access to tcp port {{ api_port }}
      community.general.ufw:
        rule: allow
        port: '{{ api_port }}'
        proto: tcp

    - name: install binary
      ansible.builtin.copy:
        src: "{{ binary_path }}"
        dest: /usr/local/bin/btcapi
        owner: root
        group: root
        mode: '0777'
        
    - name: install service file
      ansible.builtin.template:
        src: ./service.j2
        dest: /etc/systemd/system/btcapi.service
        owner: root
        group: root
        mode: '0744'

    - name: start service
      systemd:
        name: btcapi
        state: restarted
        enabled: yes
        daemon_reload: yes