name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
       - main
  pull_request:
    branches:
       - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
  deploy:
    needs: ['test']
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - run: npm install

      - name: Package into node binary
        id: pkg
        uses: lando/pkg-action@v2
        with:
          entrypoint: app.js
          arch: amd64
          node-version: node16
          os: linux
          upload: false
      
      - name: get IP address - dev
        if: github.event_name == 'pull_request'
        id: ip-dev
        run: echo "::set-output name=ip-address::$(aws ssm get-parameter --with-decryption --name "/dev/vm/ip" | jq -r .Parameter.Value)"
        shell: bash

      - name: get IP address - prod
        if: github.event_name == 'push'
        id: ip-prod
        run: echo "::set-output name=ip-address::$(aws ssm get-parameter --with-decryption --name "/prod/vm/ip" | jq -r .Parameter.Value)"
        shell: bash

      - name: ansible - dev
        if: github.event_name == 'pull_request'
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ops/ansible/playbook.yml
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          options: |
            -i "${{ steps.ip-dev.outputs.ip-address }},"
            --extra-vars mongo=${{ secrets.MONGO_CONNECTION_STRING_DEV }}
            --extra-vars jwt=${{ secrets.JWT_KEY }}
            --extra-vars bin="../../${{ steps.pkg.outputs.file }}"
            --verbose

      - name: ansible - prod
        if: github.event_name == 'push'
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ops/ansible/playbook.yml
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          options: |
            -i "${{ steps.ip-prod.outputs.ip-address }},"
            --extra-vars mongo=${{ secrets.MONGO_CONNECTION_STRING_PROD }}
            --extra-vars jwt=${{ secrets.JWT_KEY }}
            --extra-vars bin="../../${{ steps.pkg.outputs.file }}"
            --verbose
  
  post-deploy:
    needs: ['deploy']
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2