name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
       - main
  pull_request:
    branches:
       - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      
      - uses: ./.github/actions/plan
        if: github.event_name == 'pull_request'
      

  
  deploy:
    needs: ['test']
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      
      - uses: ./.github/actions/apply
      
      - run: npm install

      - name: Package into node binary
        id: pkg
        uses: lando/pkg-action@v2
        with:
          entrypoint: app.js
          arch: amd64
          node-version: node16
          os: linux
          upload: false

      - name: get vars from parameter store
        id: ssm-values
        run: |
          echo "::set-output name=ip-address::$(aws ssm get-parameter --with-decryption --name "/vm/ip" | jq -r .Parameter.Value)"
          echo "::set-output name=ses-iam-key::$(aws ssm get-parameter --with-decryption --name "/ses/userKey" | jq -r .Parameter.Value)"
          echo "::set-output name=ses-iam-secret::$(aws ssm get-parameter --with-decryption --name "/ses/userSecret" | jq -r .Parameter.Value)"
        shell: bash

      - name: ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ops/ansible/playbook.yml
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          options: |
            -i "${{ steps.ssm-values.outputs.ip-address }},"
            --extra-vars mongo=${{ secrets.MONGO_CONNECTION_STRING_PROD }}
            --extra-vars jwt=${{ secrets.JWT_KEY }}
            --extra-vars bin="../../${{ steps.pkg.outputs.file }}"
            --extra-vars aws_key="${{ steps.ssm-values.outputs.ses-iam-key }}"
            --extra-vars aws_secret="${{ steps.ssm-values.outputs.ses-iam-secret }}"
            --verbose
  
  post-deploy:
    needs: ['deploy']
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2