name: Build and Deploy Prod
on:
  workflow_dispatch:
  push:
    branches:
       - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
  deploy:
    needs: ['test', 'build']
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
  
  post-deploy:
    needs: ['deploy']
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2